
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_DATA_H
#define TESTSLAVE_DATA_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_Data_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_Data_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data_Data;

#endif // TESTSLAVE_DATA_H
